depth = -999;
gameframe_init();
global.gameframe_caption_text = "Pizza Tower: The Morning Star";
global.gameframe_caption_font = fnt_caption;
global.gameframe_caption_icon = spr_ico;
mouse_in_window = false;
gameframe_visible_time = 60;
mouseX = mouse_x;
mouseY = mouse_y;
global.SfxVolume = 1;
global.MusicVolume = 1;
global.MasterVolume = 1;
global.unfocusedmute = true;
master = global.MasterVolume;
